language: python
python:
- 3.8
- 3.7
- 3.6
sudo: required
dist: xenial
install: pip install -U tox-travis coveralls
script: tox
after_success:
  - coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  server: https://test.pypi.org/legacy/ # Remove for deployment to official PyPi repo
  password:
    secure: NYNI4VfvwiF46/06n6NjEygtrddOTRxle5mSCxwSh38ITQU3x0piowSULDH6dSDGl7jGQNCrhjgdclzxiVpGEENdkRDxU6ZKxYx57PzsSp+ExueJ52V/byH8YIFYxPyQn++xXmYcg1PF/zDq+ln+trPQKw5/042OraXeAU8OflfM/VqvCAWT9xyqJLjPqP1ndb3RlsVlSaLEGQyGqmr0cojAQE2tZUX8+KC+prP4vEpDxcuAT6EH1fE6bKDp1Xfd8x1XTXbW1A1hUeHqjp53kNRH0TbVQ/iMF5MipwVL8jxW0u7qo2D5bd017p1jMUE38eFmd7MYXYgmvWW6rOc1FGTfW/dZWq5vWMwREzudpvDNm/RhGW0RnVEJJJolbFr2jGJAJ1h6WtJiyt0eWNkbRnfHRW2DjGOR05cJCATGgE40rXwXoNjkQFximVZZaBMwC+arSaEiHi6UWfWAi6D26sWNMtM0TI+I7LiUVrcs36BlL32I+3lfZZU7CM2xTpRlADs9jGf1yRd0ujKqTyVrYGSV4ZqCVVkwgTsBlohk/F8uNISUUTwkECbtwE+zXG10yiZbMES8sxe5sTIzGLkQ2uHjzynq4/GtaxOwZdA+4Qf4ab1UT5b0f28VI9a5Th30Z/MIHhrsVGNvHHLu8YF2Y9Qx8d1WvJJ4NTyIH+6zE1g= # TestPyPi
    # secure: Wo6nWS00bZMDXVMlQtu27U0nqMv7c16YvPlp6/DFe1rAwTubbt8MqaVaT708ByVw9nw7NvlcYSOoG+FNG6DQijfDkhfE1+9zwRqdz+cSZW75l/qcvwgq+8L8a15j5utomOz6d7BWJFQrqwVZ8m891OFZ+xLNwnsW9pTfRrjWlPmoAXISC+W8Yfemk4gRrO6X52Db8scapvobf1rO0CgFurNG924dr+wNCVfXhYbxLiCGT3qgT2m3sP9ZeCiZZ0ysabIiJgGZ+BQ5A7B8zDGMAEL5u0IDpWcl1qruzRQRm2JftVA4Lv9M8T/uy1tSId5gAXlw/IEUPxJvwilf2hi0uzp8y08q3Fap+bflxxloCmhb5K+SPM92TJPXa9B7VdbNVTJV4Whdybk2NvWxp6wYLwdgKhEVHPVY9knnEbl16ftp4UP5zD9DpkWU6sVrSf4NWzAEDIXGmakbS71zJxirQbzgb0mQXu1UveIhFevlEAr/z6YzZdX49QhNmlWYq+fgD+fEcXA7s2PcydDuaU7bKxH//PykF+wj8x7buZx5m2FzHTGRSTLUulg+iULYKy69X0mhcVAnYbMkSydoIAbUF90JKlyciZmfOoIVQGK66ZGc05YeJhrFVq1I9bdbbQf+5dCW1hSbgDSwWTrIN4fKbB2CnW3qSJZ/baZEZn03Gik= # PyPi
  on:
    # tags: true
    repo: mattsaxon/pysonofflan
    branch: V3-Firmware
    python: 3.7
